version: '3.8'

services:
  delivery-fee-calculator:
    container_name: delivery-fee-calculator-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443